name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          generate_code: true

      - name: Integration Test
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y;
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          cd example
          flutter drive --driver=integration_test/driver.dart --target=integration_test/js_service_test.dart -d linux
